### PR TITLE
fix the one-way binding attribute.

### LINKED ISSUE #131: Using the oneWay option doesn't ever send the correct value.
### Version of x-select:
2.2.0

### Expected Behavior
Using `oneWay` should send the new selected value with the action.

### Actual Behavior
Using `oneWay` does NOT send the new value. 

### Steps To Reproduce:
1. Add `oneWay=true` to your x-select
- Add an action
- Make a new selection
- Watch the value not update

### Ember Twiddle / Example repo / Failing test:

https://github.com/thefrontside/emberx-select/tree/fix-two-way-removal this branch

### PR DESCRIPTION
**Pull request by cowboyd**
This separates the `read` operation from the `write` operation which turns out to be a very handy thing. It turns out that reading a multi select value and a single select value is the only difference.

So upon an update, we read the next value (which depends on the selection type) and then, regardless of whethere it is multi or not, we `set` the value if it is a two-way binding.

fixes #131, closes #129

### CODE REVIEW

File: addon/components/x-select.js [hunk 1]
```diff
@@ -62,11 +62,11 @@ export default Ember.Component.extend({
    *   {{!options here ....}}
    * {{/x-select}}
    *
-   * @property oneWay
+   * @property one-way
    * @type Boolean
    * @default false
    */
-  oneWay: false,
+  'one-way': false,
```
Comment (Robdel12) [inline addon/components/x-select.js]: Can we create a line below this that aliases `oneWay` to `one-way` but only ref `one-way` in the docs? Only because I cut the release of 2.2 already and this would break semver :( 

```js
"one-way": Ember.computed.alias('oneWay'),
```

**Comment by Robdel12** [comment]
I think you still need to update the `focusOut`, `blur, and `click` actions since those are still being sent with `this.get('value)`.

**Comment by cowboyd** [comment]
Nice catch. I've added that fix, and updated the testcases.

File: addon/components/x-select.js (hunk 1 above)
Comment (cowboyd) [inline addon/components/x-select.js]: done!

**Comment by Robdel12** [comment]
LGTM! going to merge!
